import { analyzeProductUrl } from "../src/lib/scrape/extractor.ts";
const r = await analyzeProductUrl("https://es.aliexpress.com/item/1005010540843715.html");
console.log("OK:", r.success, "| METODO:", r.method);
console.log("NOMBRE:", r.product?.name);
console.log("PRECIO:", r.product?.price);
console.log("VENDEDOR:", r.product?.seller_name);
console.log("FABRICANTE:", r.product?.manufacturer_name);
console.log("EMAIL:", r.product?.manufacturer_email);
console.log("DIRECCION:", r.product?.manufacturer_address);
console.log("EU:", r.product?.eu_responsible);
console.log("CONTACTS:", JSON.stringify((r.product?.contacts || []).map((c) => ({ t: c.contact_type, e: c.email, n: c.company })), null, 1));